title: My Website
author: Salah Elyasi
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I’m glad you are here. I plan to talk about Html and css …



# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
